//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 01:30:43 AM MSK 
//


package entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Company", propOrder = {
    "name",
    "address",
    "rate"
})
public class Company {

    @XmlElement(required = true)
    private String name;
    @XmlElement(required = true)
    private Address address;
    private int rate;


    public String getName() {
        return name;
    }


    public void setName(String value) {
        this.name = value;
    }


    public Address getAddress() {
        return address;
    }


    public void setAddress(Address value) {
        this.address = value;
    }


    public int getRate() {
        return rate;
    }


    public void setRate(int value) {
        this.rate = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Company company = (Company) o;
        return rate == company.rate &&
                Objects.equals(name, company.name) &&
                Objects.equals(address, company.address);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, address, rate);
    }
}
