//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 01:30:43 AM MSK 
//


package entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataPlan", propOrder = {
    "countOfGigabytes"
})
public class DataPlan
    extends PostPaidPlan
{

    @XmlElement(required = true)
    private int countOfGigabytes;


    public int getCountOfGigabytes() {
        return countOfGigabytes;
    }


    public void setCountOfGigabytes(int value) {
        this.countOfGigabytes = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        DataPlan dataPlan = (DataPlan) o;
        return countOfGigabytes == dataPlan.countOfGigabytes;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), countOfGigabytes);
    }
}
