//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 01:30:43 AM MSK 
//


package entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FullPlan", propOrder = {
    "countOfGigabytes",
    "countOfMinutes"
})
public class FullPlan
    extends PostPaidPlan
{

    @XmlElement(required = true)
    private int countOfGigabytes;
    @XmlElement(required = true)
    private int countOfMinutes;


    public int getCountOfMinutes() {
        return countOfMinutes;
    }


    public void setCountOfMinutes(int value) {
        this.countOfMinutes = value;
    }


    public int getCountOfGigabytes() {
        return countOfGigabytes;
    }


    public void setCountOfGigabytes(int value) {
        this.countOfGigabytes = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        FullPlan fullPlan = (FullPlan) o;
        return countOfGigabytes == fullPlan.countOfGigabytes &&
                countOfMinutes == fullPlan.countOfMinutes;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), countOfGigabytes, countOfMinutes);
    }
}
