//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 01:30:43 AM MSK 
//


package entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plan", propOrder = {
        "name",
        "dateOfIssue",
        "dateOfExpiry",
        "status",
        "company",
        "minuteCost",
        "smsCost",
        "gigabyteCost"
})
@XmlSeeAlso({
        PrepaidPlan.class,
        PostPaidPlan.class
})
public abstract class Plan {

    @XmlElement(required = true)
    private String name;
    @XmlElement(required = true)
    private String dateOfIssue;
    @XmlElement(required = true)
    private String dateOfExpiry;
    @XmlElement(required = true)
    private String status;
    @XmlElement(required = true)
    private Company company;
    private double minuteCost;
    private double smsCost;
    private double gigabyteCost;


    public String getName() {
        return name;
    }


    public void setName(String value) {
        this.name = value;
    }


    public String getDateOfIssue() {
        return dateOfIssue;
    }


    public void setDateOfIssue(String value) {
        this.dateOfIssue = value;
    }


    public String getDateOfExpiry() {
        return dateOfExpiry;
    }


    public void setDateOfExpiry(String value) {
        this.dateOfExpiry = value;
    }

    public String getStatus() { return status; }

    public void setStatus(String status) { this.status = status; }

    public Company getCompany() {
        return company;
    }


    public void setCompany(Company value) {
        this.company = value;
    }


    public double getMinuteCost() {
        return minuteCost;
    }


    public void setMinuteCost(double value) {
        this.minuteCost = value;
    }


    public double getSmsCost() {
        return smsCost;
    }


    public void setSmsCost(double value) {
        this.smsCost = value;
    }


    public double getGigabyteCost() {
        return gigabyteCost;
    }


    public void setGigabyteCost(double value) {
        this.gigabyteCost = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Plan plan = (Plan) o;
        return Double.compare(plan.minuteCost, minuteCost) == 0 &&
                Double.compare(plan.smsCost, smsCost) == 0 &&
                Double.compare(plan.gigabyteCost, gigabyteCost) == 0 &&
                Objects.equals(name, plan.name) &&
                Objects.equals(dateOfIssue, plan.dateOfIssue) &&
                Objects.equals(dateOfExpiry, plan.dateOfExpiry) &&
                Objects.equals(status, plan.status) &&
                Objects.equals(company, plan.company);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, dateOfIssue, dateOfExpiry, status, company, minuteCost, smsCost, gigabyteCost);
    }

}
