//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 01:30:43 AM MSK 
//


package entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostPaidPlan", propOrder = {
    "subscription",
    "fee"
})
@XmlSeeAlso({
    AudioPlan.class,
    DataPlan.class,
    FullPlan.class
})
public abstract class PostPaidPlan
    extends Plan
{

    @XmlElement(required = true)
    private String subscription;
    private int fee;


    public String getSubscription() {
        return subscription;
    }


    public void setSubscription(String value) {
        this.subscription = value;
    }


    public int getFee() {
        return fee;
    }


    public void setFee(int value) {
        this.fee = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        PostPaidPlan that = (PostPaidPlan) o;
        return fee == that.fee &&
                Objects.equals(subscription, that.subscription);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), subscription, fee);
    }
}
